const addressesData = [
      {
        id: 1,
        title: 'title',
        firstName: 'first name',
        lastName: 'last name',
        addressLine1: 'address line 1',
        addressLine2: 'address line 2',
        city: 'city',
        zipPostal: 'W1J7BU',
        phoneNumber: '09238198312',
        isDefaultShipping: false,
        isDefaultBilling: false,
      },
      {
        id: 2,
        title: 'title',
        firstName: 'first name',
        lastName: 'last name',
        addressLine1: 'address line 1',
        addressLine2: 'address line 2',
        city: 'city',
        zipPostal: 'W1J7BU',
        phoneNumber: '09238198312',
        isDefaultShipping: false,
        isDefaultBilling: false,
      },
      {
        id: 3,
        title: 'title',
        firstName: 'first name',
        lastName: 'last name',
        addressLine1: 'address line 1',
        addressLine2: 'address line 2',
        city: 'city',
        zipPostal: 'W1J7BU',
        phoneNumber: '09238198312',
        isDefaultShipping: true,
        isDefaultBilling: true,
      },
      {
        id: 4,
        title: 'title',
        firstName: 'first name',
        lastName: 'last name',
        addressLine1: 'address line 1',
        addressLine2: 'address line 2',
        city: 'city',
        zipPostal: 'W1J7BU',
        phoneNumber: '09238198312',
        isDefaultShipping: false,
        isDefaultBilling: false,
      }
];

export { addressesData };
